info:
  name: View System Configuration
  type: http
  seq: 1

http:
  method: GET
  url: "{{baseUrl}}system-configuration"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
